from app.models.hint import db, Hint, environment, SCHEMA
from sqlalchemy.sql import text

def seed_hints():
    john_summit_hint = Hint(artist_id=1, hint="This Chicago-born DJ used to make house-production tutorials on YouTube and went viral for the following drunken question, 'Miamiii how we feelin!'")
    deadmau5_hint = Hint(artist_id=2, hint="Known for his iconic helmet, this artist also partners with iconic artist Kaskade to form 'Kx5'")
    carl_cox_hint = Hint(artist_id=3, hint="A legend in the techno scene, this British artist held a long-standing residency at Space Ibiza.")
    armin_van_buuren_hint = Hint(artist_id=4, hint="A trance music icon from the Netherlands, this artist has claimed the number one DJ spot multiple times.")
    martin_garrix_hint = Hint(artist_id=5, hint="This artist shot to fame with a hit single at just 17 years old.")
    diplo_hint = Hint(artist_id=6, hint="One-third of Major Lazer, this American artist has collaborated with the likes of Skrillex and Sia.")
    tiesto_hint = Hint(artist_id=7, hint="Considered one of trance music's pioneers, this Dutch artist won a Grammy for remixing John Legend's 'All of Me'.")
    skrillex_hint = Hint(artist_id=8, hint="This artist rose to prominence in the early 2010s with his dubstep productions, but has since changed his sound dramatically, famously performing with fred again... and Fourtet at Coachella 2023.")
    calvin_harris_hint = Hint(artist_id=9, hint="This iconic artist boasts multiple billion streamed songs, featuring pop superstars such as Rihanna and Ellie Golding.")
    above_and_beyond_hint = Hint(artist_id=10, hint="A British trance group known for their emotive music, this trio hosts the weekly radio show 'Group Therapy'.")
    eric_prydz_hint = Hint(artist_id=11, hint="From Sweden, this DJ is renowned for his epic live shows, incorporating holograms and stunning visuals into his performances.")
    nina_kraviz_hint = Hint(artist_id=12, hint="Hailing from Russia, this artist is not only a DJ but also a trained dentist and a former journalist.")
    richie_hawtin_hint = Hint(artist_id=13, hint="Known for his pioneering work in minimal techno, this DJ often performs under his alias Plastikman.")
    charlotte_de_witte_hint = Hint(artist_id=14, hint="A Belgian DJ known for her dark and atmospheric techno sets, this artist has gained a dedicated following worldwide.")
    david_guetta_hint = Hint(artist_id=15, hint="This DJ and producer is one of the pioneers of the EDM genre, having produced numerous chart-topping hits and is the #1 streamed DJ on Spotify.")
    adam_beyer_hint = Hint(artist_id=16, hint="From Sweden, this artist is the founder of the Drumcode record label and is known for his uncompromising techno sound.")
    steve_aoki_hint = Hint(artist_id=17, hint="This artist is known for his energetic live performances and his label Dim Mak Records. Look out for flying cakes!")
    alison_wonderland_hint = Hint(artist_id=18, hint="This Australian artist gained prominence with her unique blend of electronic and trap music and her captivating live performances.")
    dillon_francis_hint = Hint(artist_id=19, hint="From Los Angeles, this artist is known for his eclectic style that blends elements of moombahton, trap, and house music.")
    kaskade_hint = Hint(artist_id=20, hint="This pioneering DJ maintains a residency at XS Nightclub in Las Vegas and is the owner of popular record label, 'Arkade'.")
    marshmello_hint = Hint(artist_id=21, hint="Known for his signature helmet, this American DJ gained widespread popularity with hits like 'Alone' and 'Happier'.")
    porter_robinson_hint = Hint(artist_id=22, hint="This genre-less artist gained acclaim for his debut album 'Worlds' and is known for his innovative and emotional approach to electronic music. He is also the organizer of 'Second Sky', a bay-area festival.")
    paul_van_dyk_hint = Hint(artist_id=23, hint="His popular release, 'For An Angel' (1995), cemented this German artist as one of the pioneers of trance music and has won multiple awards for his work.")
    excision_hint = Hint(artist_id=24, hint="Known for his heavy dubstep sound and his bass-heavy live performances, this Canadian DJ is a prominent figure in the dubstep scene, organizing multiple bass festivals across the country.")
    knock2_hint = Hint(artist_id=25, hint="This San Diego DJ and producer gained attention with his unique blend of trap, hip-hop, and bass music and has multiple music kits in Counter Strike.")
    iso_xo_hint = Hint(artist_id=26, hint="With his unique blend of trap and bass music, this artist has gained a dedicated following in the electronic music scene and had multiple sell-out nights at the Shrine LA venue.")
    rl_grime_hint = Hint(artist_id=27, hint="This DJ and producer is known for his hard-hitting trap beats and his annual Halloween mixtapes and is the founder of the 'Sable Valley' record label.")
    baauer_hint = Hint(artist_id=28, hint="Best known for his viral hit 'Harlem Shake', this American DJ and producer has since gained acclaim for his experimental trap music.")
    san_holo_hint = Hint(artist_id=29, hint="Hailing from the Netherlands, this artist gained popularity with his future bass and trap-influenced tracks, posting many of his early music on Trap Nation's YouTube channel. His 2017 release, 'Light', propelled him into stardom.")
    whethan_hint = Hint(artist_id=30, hint="A young talent from the United States, this artist gained attention with his remixes of popular tracks and his unique production style.")
    flume_hint = Hint(artist_id=31, hint="Hailing from Australia, this artist gained widespread acclaim with his self-titled debut album and is known for his innovative production techniques.")
    seven_lions_hint = Hint(artist_id=32, hint="This DJ and producer is known for his melodic dubstep and trance-inspired tracks, as well as his emotionally charged live performances. A notable song of his is named after a piece of land completely surrounded by water.")
    said_the_sky_hint = Hint(artist_id=33, hint="With his emotional and uplifting music, this American artist has gained a dedicated following in the electronic music community, with notable songs like 'Other Side'.")
    dabin_hint = Hint(artist_id=34, hint="Hailing from Canada, this artist is known for his melodic dubstep and future bass productions, as well as his live performances as a guitarist.")
    liquid_stranger_hint = Hint(artist_id=35, hint="Known for his diverse range of bass music, this Swedish artist is the founder of the Wakaan record label.")
    space_laces_hint = Hint(artist_id=36, hint="This American artist is known for his heavy dubstep and drum and bass productions, his collaborations with artists like Excision as well as being a part of hard-dubstep group, MASTERHAND.")
    acraze_hint = Hint(artist_id=37, hint="Hailing from the United States, this artist gained attention with his unique blend of bass and house music, most notably with his hit, 'Do It to It'.")
    armnhmr_hint = Hint(artist_id=38, hint="This American DJ and production duo gained acclaim for their emotional and melodic bass music, often incorporating anime clips into their sets.")
    zeds_dead_hint = Hint(artist_id=39, hint="A Canadian electronic music duo known for their diverse range of styles, including dubstep, drum and bass, and house music.")
    dog_blood_hint = Hint(artist_id=40, hint="This collaborative project between Skrillex and Boys Noize is known for its high-energy performances and its blend of techno and house music.")
    galantis_hint = Hint(artist_id=41, hint="A Swedish electronic music duo known for their catchy melodies and energetic performances, this group gained fame with hits like 'Runaway (U & I)' and 'No Money'.")
    slander_hint = Hint(artist_id=42, hint="This American DJ duo gained popularity with their unique blend of melodic and bass-heavy music, as well as their high-energy live shows.")
    yellow_claw_hint = Hint(artist_id=43, hint="Hailing from the Netherlands, this DJ duo is known for their eclectic mix of trap, hardstyle, and EDM. They also produce house music under alias, €URO TRA$H.")
    flosstradamus_hint = Hint(artist_id=44, hint="An American DJ duo known for pioneering the trap genre and their high-energy live performances, this group (since split) has collaborated with artists like Travis Porter and Major Lazer.")
    nervo_hint = Hint(artist_id=45, hint="Australian DJ duo and twin sisters, this duo is known for their energetic performances and their work as songwriters and producers for artists like David Guetta and Kylie Minogue.")
    chainsmokers_hint = Hint(artist_id=46, hint="This American DJ duo have a tendency to steal mattresses from their roommates from Boulder.")
    chase_and_status_hint = Hint(artist_id=47, hint="A British electronic music production duo, this group is known for their blend of drum and bass, dubstep, and other genres.")
    maup_hint = Hint(artist_id=48, hint="A French DJ and producer known for his energetic house music sets and his collaborations with artists like Robin Schulz and David Guetta.")
    virtual_hint = Hint(artist_id=49, hint="This American DJ duo gained attention for their unique blend of bass music and virtual reality-inspired aesthetic.")
    chainsmokers_hint_2 = Hint(artist_id=50, hint="This American DJ duo gained worldwide fame with hits like 'Closer' and 'Don't Let Me Down', as well as their crossover pop sound.")
    jauz_hint = Hint(artist_id=51, hint="An American DJ and producer known for his bass house and dubstep productions, this artist gained attention with tracks like 'Feel the Volume' and 'Rock the Party'.")
    reaper_hint = Hint(artist_id=52, hint="This mysterious artist is known for his dark and atmospheric bass music, as well as his unique visual aesthetic.")
    sullivan_king_hint = Hint(artist_id=53, hint="Blending heavy metal and electronic music, this American artist is known for his guitar-driven bass music.")
    subtronics_hint = Hint(artist_id=54, hint="An American DJ and producer known for his heavy dubstep sound and his collaborations with artists like Excision and Griz.")
    eliminate_hint = Hint(artist_id=55, hint="This American artist is known for his high-energy bass music and his innovative sound design.")
    fisher_hint = Hint(artist_id=56, hint="An Australian DJ and producer known for his infectious house music beats and his charismatic personality.")
    fred_again_hint = Hint(artist_id=57, hint="A British DJ and producer known for his genre-blurring productions and his collaborations with artists like Ed Sheeran and Stormzy.")
    matroda_hint = Hint(artist_id=58, hint="Hailing from Croatia, this artist is known for his bass house and future house productions.")
    discolines_hint = Hint(artist_id=59, hint="This mysterious artist gained attention with his unique blend of disco and house music, as well as his retro aesthetic.")
    chyl_hint = Hint(artist_id=60, hint="A rising talent in the electronic music scene, this artist is known for his energetic bass music and his dynamic live performances.")
    wooli_hint = Hint(artist_id=61, hint="This American artist gained attention for his heavy dubstep sound and his collaborations with artists like Excision and Seven Lions.")
    nghtmre_hint = Hint(artist_id=62, hint="An American DJ and producer known for his trap and bass music productions, this artist has collaborated with artists like Zeds Dead and SLANDER.")
    trivecta_hint = Hint(artist_id=63, hint="Hailing from the United States, this artist is known for his melodic bass music and his emotionally charged productions.")
    k_id_hint = Hint(artist_id=64, hint="This mysterious artist is known for his unique blend of bass and experimental electronic music, as well as his distinctive visual aesthetic.")
    wax_motif_hint = Hint(artist_id=65, hint="An Australian DJ and producer, this artist is known for his energetic house music sets and his collaborations with artists like Destructo and A-Trak.")
    valentino_khan_hint = Hint(artist_id=66, hint="Known for his energetic and eclectic style, this American artist is a versatile producer who has worked with artists across various genres.")
    gryffin_hint = Hint(artist_id=67, hint="An American DJ and producer known for his melodic and uplifting music, this artist gained attention with tracks like 'Heading Home' and 'Tie Me Down'.")
    svdden_death_hint = Hint(artist_id=68, hint="This American artist is known for his heavy dubstep sound and his energetic live performances.")
    kai_wachi_hint = Hint(artist_id=69, hint="Hailing from the United States, this artist is known for his unique blend of bass music and his hard-hitting productions.")
    ZHU_hint = Hint(artist_id=70, hint="This Chinese-American artist gained attention for his deep house and indie dance productions, as well as his mysterious persona.")
    ray_volpe_hint = Hint(artist_id=71, hint="An American DJ and producer known for his heavy dubstep and bass music sound, this artist has gained a dedicated following in the electronic music scene.")
    dom_dolla_hint = Hint(artist_id=72, hint="This Australian artist gained attention with his infectious house music beats and his energetic live performances.")
    DIESEL_hint = Hint(artist_id=73, hint="A multi-talented artist, this American DJ is also known for his career in professional basketball.")

    db.session.add(john_summit_hint)
    db.session.add(deadmau5_hint)
    db.session.add(carl_cox_hint)
    db.session.add(armin_van_buuren_hint)
    db.session.add(martin_garrix_hint)
    db.session.add(diplo_hint)
    db.session.add(tiesto_hint)
    db.session.add(skrillex_hint)
    db.session.add(calvin_harris_hint)
    db.session.add(above_and_beyond_hint)
    db.session.add(eric_prydz_hint)
    db.session.add(nina_kraviz_hint)
    db.session.add(richie_hawtin_hint)
    db.session.add(charlotte_de_witte_hint)
    db.session.add(david_guetta_hint)
    db.session.add(adam_beyer_hint)
    db.session.add(steve_aoki_hint)
    db.session.add(alison_wonderland_hint)
    db.session.add(dillon_francis_hint)
    db.session.add(kaskade_hint)
    db.session.add(marshmello_hint)
    db.session.add(porter_robinson_hint)
    db.session.add(paul_van_dyk_hint)
    db.session.add(excision_hint)
    db.session.add(knock2_hint)
    db.session.add(iso_xo_hint)
    db.session.add(rl_grime_hint)
    db.session.add(baauer_hint)
    db.session.add(san_holo_hint)
    db.session.add(whethan_hint)
    db.session.add(flume_hint)
    db.session.add(seven_lions_hint)
    db.session.add(said_the_sky_hint)
    db.session.add(dabin_hint)
    db.session.add(liquid_stranger_hint)
    db.session.add(space_laces_hint)
    db.session.add(acraze_hint)
    db.session.add(armnhmr_hint)
    db.session.add(zeds_dead_hint)
    db.session.add(dog_blood_hint)
    db.session.add(galantis_hint)
    db.session.add(slander_hint)
    db.session.add(yellow_claw_hint)
    db.session.add(flosstradamus_hint)
    db.session.add(nervo_hint)
    db.session.add(chainsmokers_hint)
    db.session.add(chase_and_status_hint)
    db.session.add(maup_hint)
    db.session.add(virtual_hint)
    db.session.add(chainsmokers_hint_2)
    db.session.add(jauz_hint)
    db.session.add(reaper_hint)
    db.session.add(sullivan_king_hint)
    db.session.add(subtronics_hint)
    db.session.add(eliminate_hint)
    db.session.add(fisher_hint)
    db.session.add(fred_again_hint)
    db.session.add(matroda_hint)
    db.session.add(discolines_hint)
    db.session.add(chyl_hint)
    db.session.add(wooli_hint)
    db.session.add(nghtmre_hint)
    db.session.add(trivecta_hint)
    db.session.add(k_id_hint)
    db.session.add(wax_motif_hint)
    db.session.add(valentino_khan_hint)
    db.session.add(gryffin_hint)
    db.session.add(svdden_death_hint)
    db.session.add(kai_wachi_hint)
    db.session.add(ZHU_hint)
    db.session.add(ray_volpe_hint)
    db.session.add(dom_dolla_hint)
    db.session.add(DIESEL_hint)
    db.session.commit()

def undo_hints():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.hints RESTART IDENTITY CASCADE;")
    else:
        db.session.execute(text("DELETE FROM hints"))
        
    db.session.commit()