"""empty message

Revision ID: 04e2e6ee24b7
Revises:
Create Date: 2024-04-10 15:55:37.249806

"""
from alembic import op
import sqlalchemy as sa
import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = '04e2e6ee24b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre_name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guess_name', sa.String(length=30), nullable=False),
    sa.Column('guesser_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('djs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stagename', sa.String(length=30), nullable=False),
    sa.Column('firstname', sa.String(length=30), nullable=False),
    sa.Column('lastname', sa.String(length=30), nullable=False),
    sa.Column('debut_year', sa.Integer(), nullable=False),
    sa.Column('nationality', sa.String(), nullable=False),
    sa.Column('group', sa.Boolean(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('hint', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['djs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    if environment == "production":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE genres SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE guesses SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE djs SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE hints SET SCHEMA {SCHEMA};")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hints')
    op.drop_table('djs')
    op.drop_table('users')
    op.drop_table('guesses')
    op.drop_table('genres')
    # ### end Alembic commands ###
